- name: Install tmux and required dependencies
  pacman:
    name:
    - tmux
    - git
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Link tmux configuration
  file:
    src: "{{ playbook_dir }}/config/{{ item }}"
    dest: ~/.{{ item }}
    state: link
  with_items:
  - tmux.conf
  - tmux.conf.local
  register: tmuxconf

- name: Install tmux plugins
  shell: |
    # start a server but don't attach to it
    tmux start-server
    # create a new session but don't attach to it either
    tmux new-session -d
    # install the plugins
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
    # killing the server is not required, I guess
    tmux kill-server
  when: tmuxconf.changed
