- name: Install packer (Linux)
  include: linux.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Install packer (MacOSX)
  homebrew:
    name: packer
  when: ansible_distribution == "MacOSX"
