- name: Install zsh and required dependencies (Arch)
  become: yes
  pacman:
    name:
    - zsh
    - python3
    - python-pip
    - fzf
    - bat
  when: ansible_distribution == "Archlinux"

- name: Install zsh and required dependencies (Ubuntu)
  become: yes
  apt:
    name:
    - zsh
    - python3
    - python3-pip
    - bat
  when: ansible_distribution == "Ubuntu"

- name: Clone fzf repository (Ubuntu)
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf
    update: no
  when: ansible_distribution == "Ubuntu"

- name: Install fzf (Ubuntu)
  shell: ~/.fzf/install
  args:
    creates: ~/.fzf.zsh
  when: ansible_distribution == "Ubuntu"

# TODO install fzf on ubuntu

- name: Link zsh configuration
  file:
    src: "{{ playbook_dir }}/config/{{ item }}"
    dest: ~/.{{ item }}
    state: link
  with_items:
  - zshrc

- name: Find path of zsh
  shell: which zsh
  register: whichzsh
  changed_when: False

- name: Change default shell to zsh
  become: yes
  user:
    name: "{{ lookup('env','USER') }}"
    shell: "{{ whichzsh.stdout }}"

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    update: no

- name: Install powerlevel9k theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
    update: no

- name: create custom oh-my-zsh plugin directories
  file:
    path: "~/.oh-my-zsh/custom/plugins/{{ item }}"
    state: directory
  with_items:
  - editorconfig

- name: Install custom oh-my-zsh plugins
  file:
    src: "{{ playbook_dir }}/config/oh-my-zsh-plugins/{{item}}.plugin.zsh"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item }}/{{item}}.plugin.zsh"
    state: link
  with_items:
  - editorconfig

- name: Install pywal
  become: yes
  pip:
    name: pywal
    executable: pip3
