- name: Install git (Arch)
  pacman:
    name: git
  when: ansible_distribution == "Archlinux"

- name: Install git (Ubuntu)
  apt:
    name: git
  when: ansible_distribution == "Ubuntu"

- name: Render git configuration
  template:
    src: "{{ playbook_dir }}/config/gitconfig.j2"
    dest: ~/.gitconfig
    mode: 0600
