- name: Install cfssl tools
  become: yes
  get_url:
    url: https://pkg.cfssl.org/R1.2/{{ item }}_linux-amd64
    dest: /usr/local/bin/{{ item }}
    mode: 0755
    owner: root
    group: root
  with_items:
  - cfssl-bundle
  - cfssl-certinfo
  - cfssl-newkey
  - cfssl-scan
  - cfssl
  - cfssljson
  - mkbundle
  - multirootca
