- name: Capture gotop version
  shell: gotop --version || echo unknown
  register: gotop
  changed_when: False

- name: Install gotop (Ubuntu)
  become: yes
  apt:
    deb: https://github.com/cjbassi/gotop/releases/download/{{ gotop_version }}/gotop_{{ gotop_version }}_linux_amd64.deb
  when: gotop.stdout != gotop_version and ansible_distribution == "Ubuntu"

- name: Install gotop (Arch)
  become: yes
  unarchive:
    src: https://github.com/cjbassi/gotop/releases/download/{{ gotop_version }}/gotop_{{ gotop_version }}_linux_amd64.tgz
    dest: /usr/local/bin
    remote_src: yes
  when: gotop.stdout != gotop_version and ansible_distribution == "Archlinux"
