- name: Install terraform (Linux)
  include: linux.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux"

- name: Install terraform (MacOSX)
  homebrew:
    name: terraform
  when: ansible_distribution == "MacOSX"
