- name: Install gpg (Arch)
  pacman:
    name: gnupg
  when: ansible_distribution == "Archlinux"

- name: Install gpg (Ubuntu)
  apt:
    name: gnupg
  when: ansible_distribution == "Ubuntu"

- name: Create gpg configuration directory
  file:
    path: ~/.gpg
    state: directory

- name: Link gpg configuration
  file:
    src: "{{ playbook_dir }}/config/{{ item }}"
    dest: ~/.gpg/{{ item }}
    state: link
  with_items:
  - gpg-agent.conf
  - gpgrc

- name: Render gpg.conf
  template: 
    src: "{{ playbook_dir }}/config/gpg.conf.j2"
    dest: ~/.gpg/gpg.conf
    mode: 0600
