- name: Install mercurial (Arch)
  become: yes
  pacman:
    name: mercurial
  when: ansible_distribution == "Archlinux"

- name: Install mercurial (Ubuntu)
  become: yes
  apt:
    name: mercurial
  when: ansible_distribution == "Ubuntu"

- name: Install mercurial (MacOSX)
  homebrew:
    name: mercurial
  when: ansible_distribution == "MacOSX"

- name: Render mercurial configuration
  template:
    src: "{{ playbook_dir }}/config/hgrc.j2"
    dest: ~/.hgrc
    mode: 0600
